# -*- coding: utf-8 -*-
"""Penguin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUXEKL7bd094MpsUQxi5RIIj-Rm6lmoS

# **Project - Penguin Dataset**

**Data Description:**
The dataset contains 7 columns describing penguins from the Palmer Archipelago in Antarctica.

---------
- It includes information on species, physical measurements, location, and sex.


- species: The penguin species, categorized as Chinstrap, Adélie, or Gentoo.
- culmen_length_mm: Length of the penguin's culmen (beak) in millimeters (mm).
- culmen_depth_mm: Depth of the penguin's culmen (beak) in millimeters (mm).
- flipper_length_mm: Length of the penguin's flipper in millimeters (mm).
- body_mass_g: Body mass of the penguin in grams (g).
- island: Name of the island where the penguin was found, either Dream, Torgersen, or Biscoe.
- sex: Sex of the penguin, either male or female (may include missing values).

---

**Imports and installations**
"""

# Data manipulation and analysis
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing and feature engineering
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder,PowerTransformer,StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder,RobustScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from imblearn.pipeline import Pipeline as ImbPipeline

# Model selection and evaluation
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV,StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report, ConfusionMatrixDisplay
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.feature_selection import mutual_info_regression
# Models (classic ML)
from sklearn.linear_model import LogisticRegression, LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, SVR
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.cluster import KMeans, DBSCAN
from scipy.stats import mannwhitneyu
from scipy.stats import chi2_contingency
from scipy.stats import kruskal
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Utilities
import warnings
warnings.filterwarnings('ignore')
import os
import random

# For reproducibility
np.random.seed(42)
random.seed(42)

path ="/content/penguins_size.csv"


#Replace path with your file destination penguins_size

"""**what is inside**"""

df_raw = pd.read_csv(path)
df_raw.head(5)

"""**Data Types, Rows and columns**"""

print(f"{df_raw.info()} \n{"="*15} \nRows={df_raw.shape[0]} \nColumns={df_raw.shape[1]}")

"""**columns**"""

df_raw.columns

"""### **Null values and duplicates**"""

print(f"Total null values in dataset are \n{df_raw.isnull().sum().sum()}")
print("="*20)
print("Number of Null values per column")
print(df_raw.isnull().sum())
print("="*20)
print("Percentage of null values")
df_raw.isnull().sum() / len(df_raw)*100

if df_raw.duplicated().sum() == 0:
  print("no duplicates are identified")
else:
  print(f"{df_raw.duplicated().sum()} are present")

"""**Unique Values**"""

print(df_raw.nunique(),"\n")

for i in df_raw.columns:
    print(f"--- {i} ---")
    print(df_raw[i].unique())
    print("\n")

"""**check for non NaN null values like ".", " ", "\", "/", "?"**"""

# List of common non-standard null placeholders
ghost_nulls = [".", " ", "", "/", "?", "NA", "none"]

# Check all columns to see if any contain these values
for col in df_raw.columns:
    found = df_raw[df_raw[col].astype(str).str.strip().isin(ghost_nulls)]
    if len(found) > 0:
        print(f"Found {len(found)} ghost nulls in column: {col}")
        print(f"Unique values: {found[col].unique()}\n")

"""## **Actions  -:**

**On obseravtion**

- 1)Ghost values to NaN.

- 2)Removing all Null values

"""

##1. Convert Ghost values to NaN


ghosts = [".", " ", "", "/", "?"]
df_raw = df_raw.replace(ghosts, np.nan)


#2. Remove all Null values
# Since null count is only ~3%, dropping is the most efficient choice
df_clean = df_raw.dropna().reset_index(drop=True)

#3. if any spaces in column names
df_raw.columns = df_raw.columns.str.strip()
print("Cleaning Summary:")
print(f"Original rows: {len(df_raw)}")
print(f"Cleaned rows:  {len(df_clean)}")
print(f"Rows removed:  {len(df_raw) - len(df_clean)}")
print("\nFinal Null Check:")
print(df_clean.isnull().sum())

# --- Final Audit ---

print("Final Data Types:")
print(df_clean.dtypes)
print("=" * 30)

print(f"Total Duplicate Rows: {df_clean.duplicated().sum()}")
print("=" * 30)

print("Unique Values in Categorical Columns:")
for col in df_clean.select_dtypes(include='object').columns:
    print(f"{col}: {df_clean[col].unique()}")

"""-----
# **Analysis**
-----

# **Train,Test - Split , To prevent data leakage**
"""

from sklearn.model_selection import train_test_split

#Splitting train and test data at Train 80% , and Test at 20%

train_set, test_set = train_test_split(
    df_clean,
    test_size=0.2,
    random_state=42,
    stratify=df_clean['species']
)

print(f"Train shape: {train_set.shape}")
print(f"Test shape: {test_set.shape}")

"""###  **Basic description**"""

stats = train_set.describe()
median = train_set.median(numeric_only=True)
skew = train_set.skew(numeric_only=True)

stats.loc['median'] = median
stats.loc['skewness'] = skew

stats

"""## **Univariate Analysis**

**Numerical**
"""

num_cols = train_set.select_dtypes(include=['number']).columns


fig, axes = plt.subplots(nrows=len(num_cols), ncols=2, figsize=(14, 5 * len(num_cols)))

for i, col in enumerate(num_cols):

    skew_val = train_set[col].skew()


    Q1 = train_set[col].quantile(0.25)
    Q3 = train_set[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = train_set[(train_set[col] < lower_bound) | (train_set[col] > upper_bound)][col]


    sns.histplot(train_set[col], bins=20, kde=True, ax=axes[i, 0], color='teal', edgecolor='black')
    axes[i, 0].set_title(f'{col} Distribution\n(Skewness: {skew_val:.2f})', fontweight='bold')

    sns.boxplot(x=train_set[col], ax=axes[i, 1], color='teal', flierprops={"marker": "x", "markerfacecolor": "red"})
    axes[i, 1].set_title(f'{col} Box Plot\n(Outliers: {len(outliers)})', fontweight='bold')


    axes[i, 1].set_xlabel(f'Lower Bound: {lower_bound:.1f} | Upper Bound: {upper_bound:.1f}')

plt.suptitle("Detailed Univariate Analysis: Skewness & Outlier Detection", fontsize=18, y=1.02)
plt.tight_layout()
plt.show()

"""**Observations:**

**Outlier Detection:**

All four features show 0 outliers. This indicates that the data is quite clean and does not need to perform heavy trimming or capping before training model.

**Skewness:**

culmen_length_mm (0.12) and culmen_depth_mm (-0.19) are very close to being perfectly symmetrical.

body_mass_g (0.56) shows the highest positive skew, meaning there is a longer tail of heavier penguins (likely the Gentoos).

**Multimodality:**

Notice how the histograms for culmen_length_mm and flipper_length_mm have multiple "humps." This is a classic sign that the data contains distinct groups—in this case.

#### Categorical columns
"""

train_set.describe(include='object')

cat_cols=train_set.select_dtypes(include=['object']).columns

for i in cat_cols:
  print(train_set[i].value_counts())

# Set the visual style
sns.set_theme(style="whitegrid")

# Create a figure with 3 subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for i, col in enumerate(cat_cols):
    # Sort bars by descending count for better readability
    order = train_set[col].value_counts().index

    sns.countplot(data=train_set, x=col, ax=axes[i], order=order, palette='viridis')

    # Adding titles and formatting
    axes[i].set_title(f'Distribution of {col}', fontsize=14, fontweight='bold')
    axes[i].set_xlabel('')
    axes[i].set_ylabel('Count')

    # Optional: add count labels on top of bars
    for p in axes[i].patches:
        axes[i].annotate(f'{int(p.get_height())}',
                        (p.get_x() + p.get_width() / 2., p.get_height()),
                        ha = 'center', va = 'center',
                        xytext = (0, 9),
                        textcoords = 'offset points')

plt.tight_layout()
plt.show()

"""**species:**

Count: 3 unique categories.

Observation: Adelie is the most prevalent species (117), followed by Gentoo (95). Chinstrap is the least represented (54), indicating a slight class imbalance that may require attention during model evaluation (e.g., checking F1-score instead of just Accuracy).

**island:**

Count: 3 unique locations.

Observation: Most penguins in this set are from Biscoe (128) and Dream (99). Torgersen has significantly fewer observations (39), which might mean certain species are island-specific.

**sex:**

Count: 2 unique categories (MALE/FEMALE).

Observation: The distribution is well-balanced, with MALE (139) only slightly outnumbering FEMALE (127). This confirms previous cleaning step successfully removed the ghost . values.

## **Bivariate Analysis**

**Numerical**
"""

num_cols = train_set.select_dtypes(include=['number']).columns


fig, axes = plt.subplots(2, 2, figsize=(15, 12))
axes = axes.flatten()

for i, col in enumerate(num_cols):

    sns.boxplot(data=train_set, x='species', y=col, ax=axes[i], palette='viridis')
    axes[i].set_title(f'{col} by Species', fontweight='bold')

plt.tight_layout()
plt.show()

# Pairplot colored by species
sns.pairplot(train_set, hue='species', palette='viridis', corner=True)
plt.suptitle('Bivariate Relationship by Species', y=1.02)
plt.show()

corr_matrix = train_set.select_dtypes(include=['number']).corr()

plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Heatmap of Numerical Features', fontsize=15)
plt.show()

"""**observation:**

Strongest Predictor Pair:

The scatter plot of culmen_length_mm vs. culmen_depth_mm shows the cleanest separation. Gentoos have long/shallow beaks, Chinstraps have long/deep beaks, and Adélies have short/deep beaks.

Size Correlation:

There is a very high positive correlation (0.88) between flipper_length_mm and body_mass_g. Gentoos clearly dominate the upper right quadrant of these plots, indicating they are significantly larger than the other two species.

Adélie vs. Chinstrap Overlap:

While these two species overlap significantly in body mass and flipper length, they are easily distinguished by culmen length, where Chinstraps consistently score higher.

Negative Correlations:

Culmen depth shows a moderate negative correlation with both flipper length (-0.59) and body mass (-0.50), largely because the largest species (Gentoo) has the shallowest beak depth.

## Categorical vs Target (species)
"""

# Create a 2x2 grid: Top row for Island, Bottom row for Sex
fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# --- ROW 1: ISLAND ANALYSIS ---
# Count Plot (Frequency)
sns.countplot(data=train_set, x='island', hue='species', ax=axes[0, 0], palette='viridis')
axes[0, 0].set_title('Species Count per Island', fontweight='bold')

# Box Plot (Physical Distribution - using Body Mass)
sns.boxplot(data=train_set, x='island', y='body_mass_g', hue='species', ax=axes[0, 1], palette='viridis')
axes[0, 1].set_title('Body Mass Distribution by Island', fontweight='bold')

# --- ROW 2: SEX ANALYSIS ---
# Count Plot (Frequency)
sns.countplot(data=train_set, x='sex', hue='species', ax=axes[1, 0], palette='magma')
axes[1, 0].set_title('Species Count by Sex', fontweight='bold')

# Box Plot (Physical Distribution - using Body Mass)
sns.boxplot(data=train_set, x='sex', y='body_mass_g', hue='species', ax=axes[1, 1], palette='magma')
axes[1, 1].set_title('Body Mass Distribution by Sex', fontweight='bold')

plt.tight_layout()
plt.show()

"""Island Specificity:

Gentoo penguins are found exclusively on Biscoe Island, while Chinstrap penguins are only found on Dream Island. Adélie penguins are distributed across all three islands: Torgersen, Biscoe, and Dream.

Target Imbalance:

The dataset has a slight class imbalance with Adélie being the most frequent (117) and Chinstrap the least (54).

### **Multicollinearity (VIF)**
"""

from statsmodels.stats.outliers_influence import variance_inflation_factor


vif_data = pd.DataFrame()
vif_data["feature"] = num_cols

vif_data["VIF"] = [variance_inflation_factor(train_set[num_cols].values, i) for i in range(len(num_cols))]

print("VIF Results:")
print(vif_data.sort_values(by="VIF", ascending=False))

"""### **Statistical tests for significance**


**Kruskal-Wallis H-test**

**Testing if numeric features differ by Species (Target)**
"""

stats_results = {}

for feature in num_cols:
    groups = [group[feature].values for name, group in train_set.groupby('species')]
    stat, p = kruskal(*groups)
    stats_results[feature] = p

print("\nKruskal-Wallis P-values:")
for feat, p_val in stats_results.items():
    print(f"{feat}:\n{p_val:.4e}")
    if p_val < 0.05:
      print(f"{feat} with value of {p_val:.4e} which is less than 0.05\nindiactes {feat} is statistically significant impact on Species  ✅ ")
      print("="*20)
    else:
      print(f"{feat} with {p_val:.4e} is satistically insignificant ❌")

"""- The dataset is small and less errors, so we can try here multiple paths and search for better model like impact of inclusion of certain techniques like PCA is there not

- so here we choose two pathways one is
- Path - A: hERE WE DONT carry out any specilalized techniques except SMOTE for data imbalance and data prepocessings for modeltraining

-Path - B: Here we do apply extra step which is PCA, where we do feature extraction  beacuse we have observed multicolinearity VIF scores and also correlation between variables,This PCA helps toreduce the dimensionality of the data based on high variance featuure.

# **Path-A**

- without any feature reductions changes to dataset
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from imblearn.over_sampling import SMOTE


le_sex = LabelEncoder()
le_island = LabelEncoder()



X_train = train_set.drop('species', axis=1).copy()
y_train = train_set['species'].copy()

X_train['sex'] = le_sex.fit_transform(X_train['sex'])
X_train['island'] = le_island.fit_transform(X_train['island'])


smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_resampled)

print(f"Preprocessing Complete. Resampled Shape: {X_resampled.shape}")

"""## **Diagnostic Baseline (Logistic Regression)**"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report

# Initialize Multinomial Logistic Regression
log_baseline = LogisticRegression(multi_class='multinomial', max_iter=1000, random_state=42)

# Cross-Validation
cv_scores_log = cross_val_score(log_baseline, X_train_scaled, y_resampled, cv=5)

# Fit for report
log_baseline.fit(X_train_scaled, y_resampled)

print("--- LOGISTIC REGRESSION BASELINE ---")
print(f"Mean CV Accuracy: {cv_scores_log.mean():.4f}")
print("\nClassification Report (on Training Data):")
print(classification_report(y_resampled, log_baseline.predict(X_train_scaled)))

"""- Logistic regression as basline model showed outstanding performance with Cross Validation, this help us to confirm the data preprocessing steps are working fine and valid,
- Now we can move to the random forest even though baseline model having peak performance and simple, we will try for Random forest to see any changes

# **Optimized Model** - *Random Forest *

### **Random Forest to handle the complex overlaps and multicollinearity naturally.**
"""

from sklearn.ensemble import RandomForestClassifier



# Initialize Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Cross-Validation
cv_scores_rf = cross_val_score(rf_model, X_train_scaled, y_resampled, cv=5)

rf_model.fit(X_train_scaled, y_resampled)

print("--- RANDOM FOREST MODEL ---")
print(f"Mean CV Accuracy: {cv_scores_rf.mean():.4f}")




importances = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("\nFeature Importances:")
print(importances)

"""**"Linearity"**

- Logistic Regression baseline actually outperformed the Random Forest
- Preprocessing (Scaling + SMOTE) created a training environment where a simple straight line (hyperplane) can almost perfectly separate the groups.
- So we don't need a complex ensemble model. The relationship between the bill measurements and the species is strongly linear once standardized.

**Feature Importance vs. VIF**

- Despite the 288.79 VIF we saw earlier for flipper_length_mm, the Random Forest still ranked it as the second most important feature (22.59% importance).
- The sex column is effectively useless for classification here (0.7% importance). The physical measurements are so distinct that the model doesn't need to know if the penguin is male or female to guess the species.


- As the relationship between the bill measurements and the species is strongly linear once standardized.

Now is the moment of truth. We must apply the exact same transformations to the test_set that we did to the train_set.

Do NOT apply SMOTE to the test set. We want to see how the model performs on the real distribution of the 20% of data we held back.
"""

X_test = test_set.drop('species', axis=1).copy()
y_test = test_set['species'].copy()



X_test['sex'] = le_sex.transform(X_test['sex'])
X_test['island'] = le_island.transform(X_test['island'])
X_test_scaled = scaler.transform(X_test)


test_predictions = log_baseline.predict(X_test_scaled)



print("--- FINAL TEST SET PERFORMANCE (Logistic Regression) ---")
print(classification_report(y_test, test_predictions))

"""**An accuracy of 99% on the unseen test set confirms that data preprocessing—specifically the handling of "ghost" values, scaling, and SMOTE—was highly effective.**



**using Logistic Regression as a diagnostic baseline was a masterstroke. It proved that:**


- The species are linearly separable in the feature space prepared.

- SMOTE successfully balanced the classes without causing the model to overfit to the synthetic Chinstrap data.

- Even with high multicollinearity, the "signal" in the penguin measurements is so strong that the model remains robust.

# **Path B**
"""

from sklearn.decomposition import PCA

# 1. Initialize PCA
# We'll aim to keep 95% of the variance
pca = PCA(n_components=0.95)

# 2. Fit and Transform the SCALED training data
X_train_pca = pca.fit_transform(X_train_scaled)

# 3. Transform the SCALED test data (No fitting!)
X_test_pca = pca.transform(X_test_scaled)

print(f"Original features: {X_train_scaled.shape[1]}")
print(f"Reduced features (PCA): {X_train_pca.shape[1]}")
print(f"Explained Variance Ratio: {pca.explained_variance_ratio_.sum():.4f}")

"""## **Running the PCA-Based Model**"""

# 1. Re-train Logistic Regression on PCA components
log_pca = LogisticRegression(multi_class='multinomial', max_iter=1000, random_state=42)
log_pca.fit(X_train_pca, y_resampled)

# 2. Final Test Set Evaluation
pca_predictions = log_pca.predict(X_test_pca)

print("--- PERFORMANCE WITH PCA (4 Components) ---")
print(classification_report(y_test, pca_predictions))

# 3. Check if Penguin #32 is still misclassified
# Finding index 32 in our test set results
results_pca = pd.DataFrame({'Actual': y_test, 'Predicted': pca_predictions}, index=y_test.index)
print(f"\nPrediction for Penguin #32 with PCA: {results_pca.loc[32, 'Predicted']}")

"""### **even after compressing the data into 4 independent components and removing the massive multicollinearity, the model performance remains identical (99% accuracy).**

**The Component logic:**

**PCA merged the features into a "profile." This specific Adelie penguin possesses a physical profile (long bill, specific island location) that is mathematically indistinguishable from a Chinstrap.**

**Conclusion:**


**This penguin is a "Hard Negative"—a data point that naturally sits on the wrong side of the decision boundary. No amount of feature engineering or model swapping is likely to fix this without overfitting to this one specific bird.**

# **Deployment & Visualization phase**

## **Confusion Matrix**
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, pca_predictions, labels=log_pca.classes_)


plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=log_pca.classes_)
disp.plot(cmap='Blues', values_format='d')
plt.title("Final Confusion Matrix (PCA + Logistic Regression)")
plt.show()

"""## **Model Persistence**"""

import joblib

# Saving the entire pipeline components
# We save the objects we 'fit' on the training data
model_assets = {
    'scaler': scaler,
    'pca': pca,
    'label_encoder_sex': le_sex,
    'label_encoder_island': le_island,
    'final_model': log_pca
}

joblib.dump(model_assets, 'penguin_classification_v1.pkl')
print("Model and preprocessing assets saved successfully!")